<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\HomepageContent;
use Database\Seeders\HomepageContentSeeder;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

/**
 * Freezes the translated homepage row back into its seed file.
 *
 * The third step of the content pipeline: edit French, run cms:translate
 * locally, then run this. What it writes is what a deployment will read, so
 * the API is never on the deployment path and every translated string reaches
 * production through a reviewed diff.
 */
class CmsExportSeed extends Command
{
    protected $signature = 'cms:export-seed {--dry-run : Show what would be written without touching the file}';

    protected $description = 'Export the homepage content, all locales, into its versioned seed file';

    public function handle(): int
    {
        $content = HomepageContent::first();

        if ($content === null) {
            $this->error('No HomepageContent row to export. Run db:seed first, then cms:translate.');

            return self::FAILURE;
        }

        /** @var list<string> $supported */
        $supported = config('i18n.supported_locales', []);
        $export = [];

        foreach ($content->translatable as $field) {
            $translations = $content->getTranslations($field);

            // A locale the application does not serve has no business in a file
            // the deployment executes. Refusing the whole export is deliberate:
            // dropping the entry quietly would ship a file that no longer
            // matches the row it claims to mirror.
            foreach (array_keys($translations) as $locale) {
                if (! in_array($locale, $supported, true)) {
                    $this->error(sprintf(
                        "Unsupported locale %s on field '%s'. Nothing was written.",
                        var_export($locale, true),
                        $field,
                    ));
                    Log::error('Homepage seed export refused an unknown locale', [
                        'service' => self::class,
                        'method' => 'handle',
                        'step' => 'unsupported_locale',
                        'field' => $field,
                    ]);

                    return self::FAILURE;
                }
            }

            // Sorted so that two exports of the same row produce the same file:
            // a diff should only ever show a content change.
            ksort($translations);

            // Skipping an empty field would produce a file the seeder cannot
            // consume: every translated column is NOT NULL, so a missing key
            // fails at deploy time with an opaque constraint violation. Failing
            // here puts the same problem in front of a developer instead.
            if ($translations === []) {
                $this->error("Field '{$field}' has no translations. Nothing was written.");
                Log::error('Homepage seed export refused an empty field', [
                    'service' => self::class,
                    'method' => 'handle',
                    'step' => 'empty_field',
                    'field' => $field,
                ]);

                return self::FAILURE;
            }

            $export[$field] = $translations;
            $this->line(sprintf('  <fg=green>%s</> — %d locales', $field, count($translations)));
        }

        $path = database_path(HomepageContentSeeder::DATA_FILE);

        if ($this->option('dry-run')) {
            $this->info('Dry run — '.$path.' left untouched.');

            return self::SUCCESS;
        }

        file_put_contents($path, $this->render($export));

        Log::info('Homepage seed data exported', [
            'service' => self::class,
            'method' => __FUNCTION__,
            'step' => 'written',
            'fields' => count($export),
        ]);

        $this->info('Written: '.$path);

        return self::SUCCESS;
    }

    /**
     * Builds the whole file in memory before writing it.
     *
     * Bounded by design: this exports a single row, measured at ~55 KB across
     * its five translated columns. Should this ever cover many records — the
     * blog engine, say — the accumulation has to become a stream.
     *
     * @param  array<string, array<string, string>>  $export
     */
    private function render(array $export): string
    {
        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            '/**',
            ' * Homepage content, every locale, ready to seed.',
            ' *',
            ' * Generated by `php artisan cms:export-seed` after `cms:translate` has run',
            ' * locally — never by hand, and never at deploy time. Keeping the translations',
            ' * here rather than calling the API during deployment makes a deploy offline,',
            ' * free and reproducible, and puts every translated string through code review.',
            ' *',
            ' * @see docs/homepage-content.md',
            ' */',
            'return [',
        ];

        foreach ($export as $field => $translations) {
            $lines[] = sprintf("    '%s' => [", $field);

            foreach ($translations as $locale => $value) {
                // Both halves are escaped, not just the value. This writes
                // executable PHP, and an unescaped key is a code-injection
                // vector — measured: 'fr\'] , \'X' produced a parse error in
                // the generated file before this was added.
                //
                // No test reaches this line: handle() refuses any locale
                // outside supported_locales, so a hostile key never gets here.
                // Removing the escaping breaks nothing, and the coverage report
                // still says 100%. It stays anyway — a code generator must not
                // depend on its caller's validation for its own correctness —
                // but it is belt to the validation's braces, not a verified
                // guarantee. Delete the validation and this becomes live code.
                $lines[] = sprintf(
                    '        %s => %s,',
                    $this->quote((string) $locale),
                    $this->quote($value),
                );
            }

            $lines[] = '    ],';
        }

        $lines[] = '];';

        return implode("\n", $lines)."\n";
    }

    /**
     * Single quotes keep newlines literal in the file, which is what makes the
     * bio readable in a diff rather than one line of escape sequences.
     */
    private function quote(string $value): string
    {
        return "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $value)."'";
    }
}
