<?php

declare(strict_types=1);

/**
 * Homepage content, every locale, ready to seed.
 *
 * Generated by `php artisan cms:export-seed` after `cms:translate` has run
 * locally — never by hand, and never at deploy time. Keeping the translations
 * here rather than calling the API during deployment makes a deploy offline,
 * free and reproducible, and puts every translated string through code review.
 *
 * @see CLAUDE.md — "Homepage content and the seed pipeline"
 */
return [
    'tagline' => [
        'bg' => 'Neuromatrix online — биокортекс активен',
        'cs' => 'Neuromatrix online — biocortex aktiv',
        'da' => 'Neuromatrix online — biocortex actif',
        'de' => 'Neuromatrix online — biocortex aktiv',
        'el' => 'Neuromatrix online — biocortex actif',
        'en' => 'Neuromatrix online — active biocortex',
        'es' => 'Neuromatrix online — biocortex activo',
        'et' => 'Neuromatrix online — biocortex aktiivne',
        'fi' => 'Neuromatrix online — biocortex actif',
        'fr' => 'Neuromatrix online — biocortex actif',
        'ga' => 'Neuromatrix online — biocortex actif',
        'hr' => 'Neuromatrix online — biocortex actif',
        'hu' => 'Neuromatrix online — biocortex aktív',
        'it' => 'Neuromatrix online — biocortex attivo',
        'lt' => 'Neuromatrix online — biocortex aktyvus',
        'lv' => 'Neuromatrix online — biocortex aktīvs',
        'mt' => 'Neuromatrix online — biocortex attiv',
        'nl' => 'Neuromatrix online — biocortex actief',
        'pl' => 'Neuromatrix online — biocortex aktywny',
        'pt' => 'Neuromatrix online — biocortex ativo',
        'ro' => 'Neuromatrix online — biocortex activ',
        'sk' => 'Neuromatrix online — biocortex aktívny',
        'sl' => 'Neuromatrix online — biocortex aktiven',
        'sv' => 'Neuromatrix online — biocortex actif',
    ],
    'subtitle' => [
        'bg' => 'Tech Lead // Bio-машинни интерфейси',
        'cs' => 'Tech Lead // Bio-strojová rozhraní',
        'da' => 'Tech Lead // Bio-maskine-grænseflader',
        'de' => 'Tech Lead // Bio-Maschinen-Interfaces',
        'el' => 'Tech Lead // Διεπαφές βιο-μηχανών',
        'en' => 'Tech Lead // Bio-machine Interfaces',
        'es' => 'Tech Lead // Interfaces bio-máquinas',
        'et' => 'Tech Lead // Bio-masinaate liidesed',
        'fi' => 'Tech Lead // Bio-machine-rajapinnat',
        'fr' => 'Tech Lead // Interfaces bio-machines',
        'ga' => 'Tech Lead // Comhéadanais bheo-innealra',
        'hr' => 'Tech Lead // Bio-mašinskih sučelja',
        'hu' => 'Tech Lead // Bio-machine interfészek',
        'it' => 'Tech Lead // Interfacce bio-macchine',
        'lt' => 'Tech Lead // Bio-mašinų sąsajos',
        'lv' => 'Tech Lead // Bio-mašīnu interfeisi',
        'mt' => 'Tech Lead // Interfaces bio-machines',
        'nl' => 'Tech Lead // Bio-machine interfaces',
        'pl' => 'Tech Lead // Interfejsy bio-maszynowe',
        'pt' => 'Tech Lead // Interfaces bio-máquinas',
        'ro' => 'Tech Lead // Interfețe bio-mașini',
        'sk' => 'Tech Lead // Bio-strojové rozhrania',
        'sl' => 'Tech Lead // Vmesniki bio-strojev',
        'sv' => 'Tech Lead // Bio-maskin-gränssnitt',
    ],
    'bio' => [
        'bg' => 'Tech Lead. Петнадесет години строене на неща, които трябва да издържат през нощта, когато офисите са празни и само душата на машините бди над сънят на органичните.

Седем години железопътен сектор: приложения за поддръжка, където регресия не спира формуляр, а влак — някъде на релса водеща към небитието, под дъжда.

PHP, Laravel, Vue, PostgreSQL. Пишa тестовете преди да им вярвам. Документирам лъжите на кода както и истините гравирани в силиция.

Работя в сивата зона, където сигналът вече не се различава от шума. Следа от грешка, която разкрива хаоса. Редица зелени тестове, които го освещават. Развалени био/машинни интерфейси. Професията състои по-малко в преповтаряне на код, отколкото в решаване кой от тези сигнали лъжe.

Остатъка от времето наблюдавам мъгла образуваща танцуващи ореоли над неоните, които осветяват нервните центрове на цивилизация направена от мета-информации.',
        'cs' => 'Tech Lead. Patnáct let budování věcí, které musí fungovat v noci, když jsou kanceláře prázdné a pouze duše strojů bdí nad spánkem organizmů.

Sedm let v železniční dopravě: aplikace údržby, kde regrese neimobilizuje formulář, ale vlak — někde na koleji vedoucí k nicotě, v dešti.

PHP, Laravel, Vue, PostgreSQL. Psaní testů před tím, než jim věřím. Dokumentuji lži kódu stejně jako pravdy vryté v křemíku.

Pracuji v šedé zóně, tam, kde se signál již neliší od šumu. Stopa chyby, která odhaluje chaos. Řada zelených testů, která to posvěcuje. Bio/strojová rozhraní v rozkladu. Řemeslo spočívá méně v opakovém výtěžku kódu než v rozhodování, který z těchto signálů lže.

Zbytek času sleduji, jak mrholení vytváří tančící haló na neonech osvětlujících nervové uzly civilizace vytvořené z meta-informací.',
        'da' => 'Tech Lead. Femten år brugt på at bygge ting, der skal holde om natten, når kontorerne er tomme, og kun maskinernes sjæl våger over de organiske væseners søvn.

Syv år inden for jernbaner: vedligeholdelsesapplikationer, hvor en regression ikke blot sætter en formular ud af drift, men en tog — et sted på en spor, der fører ud i intet, under regnen.

PHP, Laravel, Vue, PostgreSQL. Jeg skriver tests, før jeg tror på dem. Jeg dokumenterer kodens løgne lige så meget som sandheder gravet i silicium.

Jeg arbejder i gråzonen, hvor signalet ikke længere skelnes fra støjen. Et fejlspor, der afslører kaos. En grøn testsekvens, der helliggør det. Bio-maskine-grænseflader i uorden. Arbejdet består mindre i at gengive kode end i at afgøre, hvilket af disse signaler der løgner.

Resten af tiden ser jeg tågen danne dansende gloriapunkter omkring de neonlys, der lyser civilisationens kritiske knudepunkter, skabt af meta-information.',
        'de' => 'Tech Lead. Fünfzehn Jahre damit verbracht, Dinge zu bauen, die nachts halten müssen, wenn die Büros leer sind und nur die Seele der Maschinen über den Schlaf der Organismen wacht.

Sieben Jahre Eisenbahn: Wartungsanwendungen, bei denen eine Regression nicht ein Formular blockiert, sondern einen Zug — irgendwo auf einem Gleis, das ins Nichts führt, im Regen.

PHP, Laravel, Vue, PostgreSQL. Ich schreibe die Tests, bevor ich ihnen glaube. Ich dokumentiere die Lügen des Codes genauso wie die Wahrheiten, die im Silizium eingraviert sind.

Ich arbeite in der Grauzone, wo sich das Signal nicht mehr vom Rauschen unterscheidet. Eine Fehler-Trace, die das Chaos offenbart. Eine grüne Test-Suite, die es heiligt. Bio/Maschinen-Interfaces, die auseinanderfallen. Der Beruf besteht weniger darin, Code auszuspucken, als vielmehr zu entscheiden, welches dieser Signale lügt.

In der übrigen Zeit beobachte ich, wie der Sprühregen tanzende Halos auf den Neonlichtern bildet, die die Nervenzentren einer aus Meta-Informationen bestehenden Zivilisation beleuchten.',
        'el' => 'Tech Lead. Δεκαπέντε χρόνια να χτίζω πράγματα που πρέπει να αντέχουν τη νύχτα, όταν τα γραφεία είναι άδεια και μόνο η ψυχή των μηχανών φυλάει τον ύπνο των οργανικών.

Επτά χρόνια σιδηροδρομικά: εφαρμογές συντήρησης όπου μια παλινδρόμηση δεν ακινητοποιεί μια φόρμα, αλλά ένα συρμό — κάπου σε μια σιδηροτροχιά που οδηγεί στο κενό, κάτω από τη βροχή.

PHP, Laravel, Vue, PostgreSQL. Γράφω τα τεστ πριν τα πιστέψω. Τεκμηριώνω τα ψέματα του κώδικα όσο και τις αλήθειες χαραγμένες στο πυρίτιο.

Δουλεύω στη γκρίζα ζώνη, εκεί όπου το σήμα δεν ξεχωρίζεται πλέον από τον θόρυβο. Ένα ίχνος σφάλματος που αποκαλύπτει το χάος. Μια σειρά πράσινων τεστ που το αγιάζει. Διεπαφές βιο/μηχανών σπασμένες. Το επάγγελμα συνίσταται λιγότερο στο να ξανακερνάω κώδικα παρά στο να αποφασίζω ποιο από αυτά τα σήματα λέει ψέματα.

Τον υπόλοιπο χρόνο, παρατηρώ τη λεπτή βροχή να σχηματίζει χορευτικές αλωνιές στα neon που φωτίζουν τα κρίσιμα κέντρα ενός πολιτισμού φτιαγμένου από μετα-πληροφορίες.',
        'en' => 'Tech Lead. Fifteen years building things that must hold up at night, when offices are empty and only the soul of machines watches over the sleep of the organics.

Seven years in rail: maintenance applications where a regression doesn\'t immobilize a form, but a train — somewhere on a track leading to oblivion, in the rain.

PHP, Laravel, Vue, PostgreSQL. I write tests before believing in them. I document the lies of code as much as the truths etched in silicon.

I work in the gray zone, where signal can no longer be distinguished from noise. An error trace that reveals chaos. A suite of green tests that sanctifies it. Bio/machine interfaces breaking down. The job consists less of spitting out code than deciding which of these signals lies.

The rest of the time, I watch drizzle form dancing halos on neon signs lighting the nerve centers of a civilization made of meta-information.',
        'es' => 'Tech Lead. Quince años construyendo cosas que deben funcionar por la noche, cuando las oficinas están vacías y solo el alma de las máquinas vela el sueño de los organismos.

Siete años en ferrocarriles: aplicaciones de mantenimiento donde una regresión no inmoviliza un formulario, sino un tren — en algún lugar de una vía que conduce a la nada, bajo la lluvia.

PHP, Laravel, Vue, PostgreSQL. Escribo las pruebas antes de creer en ellas. Documento las mentiras del código tanto como las verdades grabadas en el silicio.

Trabajo en la zona gris, donde la señal ya no se distingue del ruido. Una traza de error que revela el caos. Un conjunto de pruebas verde que lo santifica. Interfaces bio/máquinas desquiciadas. El oficio consiste menos en escupir código que en decidir cuál de estas señales miente.

El resto del tiempo, observo la llovizna formar halos danzantes en los neones que iluminan los centros neurálgicos de una civilización hecha de metainformaciones.',
        'et' => 'Tech Lead. Viisteist aastat asjadele, mis peavad toimima öösel, kui bürood on tühjad ja ainult masinate hing valvab orgaanikute und.

Seitse aastat raudteel: hooldusrakendused, kus regressioon ei külmuta vormi, vaid rongi — kusagil raudteel, mis viib nulliks, vihma all.

PHP, Laravel, Vue, PostgreSQL. Kirjutan testid enne, kui neis usun. Dokumenteerin koodi valetusi sama palju kui silikoonisse graveeritud tõdesid.

Töötан hallil alal, kus signaali ei saa enam mürust eristada. Veajälg, mis paljastab kaose. Roheline testide jada, mis selle pühitseb. Rikutud bio- ja masinaate liidesed. Eriala seisneb vähem koodide väljaütlemises kui selles, et otsustada, kumma neist signaalidest on vale.

Ülejäänud ajal vaatan, kuidas virtsus tekitab tantsivaid halosid noonidel, mis valgustavad tsivilisatsiooni närvikeskkonda, mis on tehtud metainfost.',
        'fi' => 'Tech Lead. Viisitoista vuotta rakentanut asioita, joiden on kestettävä yöllä, kun toimistot ovat tyhjät ja vain koneiden sielu valvoo orgaanisten unea.

Seitsemän vuotta rautatieala: ylläpito-sovellukset, joissa regressio ei pysäytä lomaketta, vaan junaa — jossain kiskoilla kohti tyhjyyttä, sateen alla.

PHP, Laravel, Vue, PostgreSQL. Kirjoitan testit ennen kuin niihin uskon. Dokumentoin koodin valheita yhtä paljon kuin pilarisiihen kaiverrettuja totuuksia.

Työskentelen harmaalla alueella, jossa signaalia ei enää erota kohinasta. Virhelokin jälki, joka paljastaa kaaoksen. Vihreä testisarja, joka pyhittää sen. Bio/machine-rajapinnat sekaisin. Ammatti koostuu vähemmän koodin toistosta ja enemmän päätöksistä siitä, mikä näistä signaaleista valehtelee.

Muulloin katselen, miten tihkusade muodostaa tanssivat valokehät neonvalojen ympärille, jotka valaisevat sivilisaation hermokeskuksia, jotka koostuvat metatiedoista.',
        'fr' => 'Tech Lead. Quinze ans à bâtir des choses qui doivent tenir la nuit, quand les bureaux sont vides et que seule l\'âme des machines veille sur le sommeil des organiques.

Sept ans de ferroviaire : des applications de maintenance où une régression n\'immobilise pas un formulaire, mais une rame — quelque part sur une voie menant au néant, sous la pluie.

PHP, Laravel, Vue, PostgreSQL. J\'écris les tests avant d\'y croire. Je documente les mensonges du code autant que les vérités gravées dans le silicium.

Je travaille dans la zone grise, là où le signal ne se distingue plus du bruit. Une trace d\'erreur qui révèle le chaos. Une suite de tests verte qui le sanctifie. Des interfaces bio/machines en déglingue. Le métier consiste moins à recracher du code qu\'à décider lequel de ces signaux ment.

Le reste du temps, je regarde la bruine former des halos dansants sur les néons qui éclairent les centres névralgiques d\'une civilisation faite de méta-informations.',
        'ga' => 'Tech Lead. Coicís bliana déag ag tógáil rudaí ar chóir dóibh fanacht ar foluain san oíche, nuair a bhíonn na hoifigí folamh agus nach bhíonn ach anam na meaisíní ag faire ar chodladh na n-orgánach.

Seacht mbliana ar an iarnród: feidhmchláir cothabhála ina bhfágann aisfhilleadh corr nach bhíonn foirm geal, ach traein — áit éigin ar bhóthar ag dul chun an neamhnioc, faoin bhfearthainn.

PHP, Laravel, Vue, PostgreSQL. Scríobhaim na tástálacha sula gcreideann mé iontu. Tugaim tuairisc ar bhréaga an chóid chomh maith le fírinní gheal sa sileacan.

Oibrím sa réimse liath, áit ar stop an comhartha a bheith ar leithéid ar an torann. Rian earráide a nochtann an chaos. Sraith tástálacha geal a shancaitheamh. Comhéadanais bheo/innealra go tuaigeach. Is lú a bhíonn san obair á bhreacadh den chóid arís ná a bheith ag cinneadh cé acu de na comharthaí seo atá ag insint brég.

An chuid eile den am, breathnaím ar an drithlín ag cruthú foluain tóireacha ar na néonainn a shoilsíonn na lárionaid néarúla ar dhomhan déanta de meta-fhaisnéis.',
        'hr' => 'Tech Lead. Petnaest godina gradnje stvari koje moraju preživjeti noć, kada su uredi prazni i samo duša mašina čuva san organskog.

Sedam godina željezničarstva : aplikacije održavanja gdje regresija ne zaustavlja obrazac, već vlak — negdje na pruzi koja vodi u ništavilo, pod kišom.

PHP, Laravel, Vue, PostgreSQL. Pišem testove prije nego što im vjerujem. Dokumentiram laži koda koliko i istine ugravirane u silicij.

Radim u sivoj zoni, gdje se signal više ne razlikuje od šuma. Trag greške koji otkriva kaos. Niz zelenih testova koji ga sankcionira. Bio/mašinska sučelja koja se raspadaju. Posao se manje svodi na ispljuvavanje koda nego na odlučivanje koji od tih signala laže.

Ostalo vrijeme gledam kako rosna stvara plesne haloe na neonima koji osvjetljavaju vitalne centre civilizacije napravljene od meta-informacija.',
        'hu' => 'Tech Lead. Tizenöt év dolgok építésén, amelyeknek éjjel is működniük kell, amikor az irodák üresen állnak és csak a gépek lelke vigyáz az organikus lények alvására.

Hét év vasútnál: karbantartási alkalmazások, ahol egy regresszió nem egy formot, hanem egy vonatot zár be — valahol egy nyomvonal végén, amely a semmi felé vezet, az esőben.

PHP, Laravel, Vue, PostgreSQL. Teszteket írok, mielőtt elhinnék bennük. A kódok hazugságait ugyanúgy dokumentálom, mint a szilíciumba vésett igazságokat.

A szürke zónában dolgozom, ahol a jel már nem különbözik a zajától. Egy hibaüzenet, amely a káoszt leleplezi. Egy zöld tesztsorozat, amely szentesíti azt. Elromlott bio/machine interfészek. A szakma nem annyira a kódok visszacsapásáról szól, mint arról, hogy eldöntsem, ezek közül a jelek közül melyik hazudik.

A többi időben azt nézem, ahogy az enyhe eső táncoló fényudvarakat képez a neonokon, amelyek egy meta-információkból álló civilizáció érző központjait világítják meg.',
        'it' => 'Tech Lead. Quindici anni a costruire cose che devono resistere di notte, quando gli uffici sono vuoti e solo l\'anima delle macchine veglia sul sonno degli organismi.

Sette anni nel ferroviario: applicazioni di manutenzione dove una regressione non blocca un modulo, ma un treno — da qualche parte su un binario che porta al nulla, sotto la pioggia.

PHP, Laravel, Vue, PostgreSQL. Scrivo i test prima di crederci. Documento le bugie del codice tanto quanto le verità incise nel silicio.

Lavoro nella zona grigia, dove il segnale non si distingue più dal rumore. Una traccia di errore che rivela il caos. Una serie di test verde che lo santifica. Interfacce bio/macchina che si sfasciano. Il mestiere consiste meno nel rigurgitare codice che nel decidere quale di questi segnali mente.

Il resto del tempo, guardo la pioggerella formare aloni danzanti sui neon che illuminano i centri nevralgici di una civiltà fatta di meta-informazioni.',
        'lt' => 'Tech Lead. Penkiolika metų kurdamas dalykus, kurie turi atlaikyti naktis, kai biurai tušti ir tik mašinų siela saugo organizmų miegą.

Septyni metai geležinkelyje: priežiūros programos, kuriose regresija neparalizuoja formos, o traukinį — kažkur bėgyje vedančiame į nieką, po lietumi.

PHP, Laravel, Vue, PostgreSQL. Testus rašau prieš jiems tikėdamas. Dokumentuoju kodo melagystes ir tiesas, išgraviruotas silicyje.

Dirbu pilkoje zonoje, kur signalas nuo triukšmo nebesiskiria. Klaidos pėdsakas, kuris atskleidžia chaosą. Žalia testų seka, kuri jį šventina. Bio/mašinų sąsajos, sulaužytos. Darbas — mažiau apie kodo pakartojimu, o daugiau apie sprendimą, kuris iš šių signalų meluoja.

Likusį laiką stebiu, kaip smulki garuojanti lietus formuoja šokančius halus ant neonų, apšviečiančių civilizacijos nervų centrus, pagamintus iš meta-informacijos.',
        'lv' => 'Tech Lead. Piecpadsmit gadi lietu veidošanā, kurām jāturēsies naktī, kad biroji ir tukši un tikai mašīnu dvēsele sargā organismu miegu.

Septiņi gadi dzelzceļa nozarē: uzturēšanas lietotnes, kur regresija neiznīcina formu, bet vilcienu — kaut kur uz sliežu ceļa, kas veda uz neko, zem lietus.

PHP, Laravel, Vue, PostgreSQL. Es rakstu testus, pirms tiem ticu. Es dokumentēju koda meli tikpat, cik patiesības, kas iegrieztas silīcijā.

Es strādāju pelēkajā zonā, kur signāls vairs neatšķiras no traucējumiem. Kļūdas izsekošana, kas atklāj haosa. Zaļa testu sērija, kas to svētī. Salauztas bio/mašīnu interfeisi. Profesija ir mazāk par koda atskaņošanu un vairāk par lēmumu pieņemšanu — kurš no šiem signāliem melo.

Pārējā laikā es vērtmaņām skaitu, kā sīkā lietus aplis uz neoniem, kas izgaismo civilizācijas neirālgiskos centrus — civilizāciju, ko veido meta-informācija.',
        'mt' => 'Tech Lead. Ħmistax-il sena biex nibnu affarijiet li għandhom jibqgħu miftuħa bil-lejl, meta l-uffiċċji huma vojta u biss l-anima tal-magni torqod fuq it-turuq tal-organiċi.

Seba\' snin ferrovjarji: applikazzjonijiet ta\' manutenzjoni fejn regressjoni ma twaqqfu formular, imma train — x\'imkien fuq triq li twassalx la nħadd iaf, taħt il-mija.

PHP, Laravel, Vue, PostgreSQL. Nikteb it-tests qabel nemmnu fihom. Niddokumenta l-kliem tal-kodiċi kemm il-verità gravata fis-silikon.

Ix-xogħol tiegħi huwa fil-zona griża, fejn is-sinjal ma jistgħux jinqasam mill-ħoss. Traċċa ta\' żball li tirrevela l-kaos. Sett ta\' tests aħdar li l-isantifika. Interfaces bio/magħna miksira. Il-mestier konsisti anqas fuq iċ-ċiklu tal-kodiċi u aktar fuq id-deċiżjoni liema minn dawn is-sinjali tkellem kliem ta\' ħażin.

Baqa\' tal-ħin, nħares ikkif il-mija tifforma halot jitkellmu fuq in-neon li jħabbat is-suwieq nevraljċi ta\' ċiviltà magħmula minn meta-informazzjonijiet.',
        'nl' => 'Tech Lead. Vijftien jaar dingen bouwen die \'s nachts overeind moeten blijven, wanneer de kantoren leeg zijn en alleen de ziel van de machines waakt over de slaap van organismen.

Zeven jaar spoorwegen: onderhoudstoepassingen waar een regressie geen formulier immobiliseert, maar een trein — ergens op een spoor dat naar het niets leidt, in de regen.

PHP, Laravel, Vue, PostgreSQL. Ik schrijf tests voordat ik erin geloof. Ik documenteer de leugens van code net zoveel als de waarheden gegraveerd in silicium.

Ik werk in de grijze zone, waar het signaal niet meer te onderscheiden is van ruis. Een stacktrace die chaos onthult. Een reeks groene tests die het heiligt. Bio-/machine-interfaces die uit elkaar vallen. Het beroep bestaat er minder uit code uit te braken dan te beslissen welk van deze signalen liegt.

De rest van de tijd kijk ik hoe motregen dansende halo\'s vormt op de neonlampen die de zenuwcentra van een beschaving gemaakt van meta-informatie verlichten.',
        'pl' => 'Tech Lead. Piętnaście lat budowania rzeczy, które muszą działać w nocy, gdy biura są puste i tylko dusza maszyn czuwa nad snem organizmów.

siedem lat w branży kolejowej: aplikacje do konserwacji, gdzie regresja nie immobilizuje formularza, ale skład — gdzieś na torze wiodącym w nicość, pod deszczem.

PHP, Laravel, Vue, PostgreSQL. Piszę testy zanim w nich uwierzę. Dokumentuję kłamstwa kodu równie ostrożnie co prawdy wyryte w krzemie.

Pracuję w szarej strefie, tam gdzie sygnał nie różni się już od szumu. Ślad błędu, który odkrywa chaos. Zielona seria testów, która go uświęca. Interfejsy bio/maszynowe w ruinie. Zawód to nie tyle wypluwanie kodu, ile decydowanie, który z tych sygnałów kłamie.

Resztę czasu patrzę, jak mżawka tworzy tańczące aureole na neonach oświetlających centrum nerwowe cywilizacji zrobionej z meta-informacji.',
        'pt' => 'Tech Lead. Quinze anos construindo coisas que precisam funcionar à noite, quando os escritórios estão vazios e apenas a alma das máquinas vela pelo sono dos organismos.

Sete anos de ferrovia: aplicações de manutenção onde uma regressão não imobiliza um formulário, mas um trem — em algum lugar numa via que leva ao nada, sob a chuva.

PHP, Laravel, Vue, PostgreSQL. Escrevo os testes antes de acreditar neles. Documento as mentiras do código tanto quanto as verdades gravadas no silício.

Trabalhho na zona cinzenta, onde o sinal não se distingue mais do ruído. Um rastreamento de erro que revela o caos. Uma suite de testes verde que o santifica. Interfaces bio/máquinas desajustadas. O trabalho consiste menos em regurgitar código do que em decidir qual destes sinais mente.

No resto do tempo, observo a garoa formar halos dançantes sobre os néons que iluminam os centros nervosos de uma civilização feita de meta-informações.',
        'ro' => 'Tech Lead. Cincisprezece ani în a construi lucruri care trebuie să funcționeze noaptea, când birourile sunt goale și doar sufletul mașinilor veghează asupra somnului organicelor.

șapte ani în feroviar: aplicații de mentenanță unde o regresie nu imobilizează o formă, ci un tren — undeva pe o cale către neant, sub ploaie.

PHP, Laravel, Vue, PostgreSQL. Scriu testele înainte să cred în ele. Documenta̦i minciuna codului la fel de mult ca și adevărurile gravate în siliciu.

Lucrez în zona gri, acolo unde semnalul nu se mai distinge de zgomot. O urmă de eroare care dezvăluie haosul. O serie de teste verde care o sanctifică. Interfețe bio/mașini în dezordine. Meseria constă mai puțin în a regurgita cod decât în a decide care dintre aceste semnale minte.

Restul timpului, privesc ploaia ușoară formând halouri dansante pe neonuri care iluminează nodurile nervoase ale unei civilizații făcute din meta-informații.',
        'sk' => 'Tech Lead. Pätnásť rokov budovania vecí, ktoré musia vydržať v noci, keď sú kancelárie prázdne a len duša strojov bdí nad spánkom organizmov.

Sedem rokov v železničnom priemysle: aplikácie údržby, kde regresia neimuobilizuje formulár, ale vlak — niekde na trati vedúcej do nicoty, v daždi.

PHP, Laravel, Vue, PostgreSQL. Píšem testy predtým, ako ich verím. Dokumentujem klamstvá kódu rovnako ako pravdy vyrytie v kremíku.

Pracujem v sivej zóne, kde sa signál už neodlišuje od šumu. Stopa chyby, ktorá odhaľuje chaos. Rada zelených testov, ktorá ho posväcuje. Bio-strojové rozhrania v rozpade. Povolanie spočíva menej v opakovom vyrážaní kódu ako v rozhodnutí, ktorý z týchto signálov klame.

Zvyšok času pozorujem, ako mrholienka tvorí tancujúce halá na neónoch osvetľujúcich nervové centrum civilizácie vytvorenej z meta-informácií.',
        'sl' => 'Tech Lead. Petnajst let gradnje stvari, ki morajo vzdržati ponoči, ko so pisarne prazne in samo duša strojev bdela nad spanjem organizmov.

Sedem let železnice: aplikacije za vzdrževanje, kjer regresija ne zaustavlja obrazca, temveč композицијо — nekje na progi, ki vodi v nič, pod dežjem.

PHP, Laravel, Vue, PostgreSQL. Teste napišem pred tem, da jim verjamem. Dokumentiram laži kode prav toliko kot resnice, vgravurane v silicij.

Delam v sivi coni, kjer se signal ne loči več od šuma. Sled napake, ki razkrije kaos. Vrsta zelenih testov, ki ga posveti. Vmesniki bio/strojev, ki se kvarijo. Poklic sestoji manj iz ponovnega izpisovanja kode kot iz odločanja, kateri od teh signalov laže.

Ostali čas gledam roso, kako tvori plesne halose na neonih, ki osvetljujejo živčne centre civilizacije, narejene iz meta-informacij.',
        'sv' => 'Tech Lead. Femton år med att bygga saker som måste fungera på natten, när kontoren är tomma och bara maskinernas själ vakar över de organiska väsendenas sömn.

Sju år inom järnväg: underhållsapplikationer där en regression inte blockerar ett formulär, utan ett tåg — någonstans på ett spår som leder till ingenting, under regnet.

PHP, Laravel, Vue, PostgreSQL. Jag skriver testerna innan jag tror på dem. Jag dokumenterar kodens lögnader lika mycket som sanningarna graverade i kisel.

Jag arbetar i gråzonen, där signalen inte längre skiljer sig från bruset. Ett felspår som avslöjar kaoset. En grön testsvit som helgar det. Bio/maskin-gränssnitt i dåligt skick. Jobbet består mindre i att upprepa kod än att avgöra vilket av dessa signaler som ljuger.

Resten av tiden betraktar jag hur duggregnet bildar dansande halor runt neonljusen som belyser hjärncentra för en civilisation gjord av metainformation.',
    ],
    'meta_description' => [
        'bg' => 'Laurent Bernard-Cardascia — Tech Lead. Архитектура, PHP/Laravel, Vue. Работя там, където сигналът вече не се различава от шума.',
        'cs' => 'Laurent Bernard-Cardascia — Tech Lead. Architektura, PHP/Laravel, Vue. Pracuji tam, kde se signál již neliší od šumu.',
        'da' => 'Laurent Bernard-Cardascia — Tech Lead. Arkitektur, PHP/Laravel, Vue. Jeg arbejder der, hvor signalet ikke længere skelnes fra støjen.',
        'de' => 'Laurent Bernard-Cardascia — Tech Lead. Architektur, PHP/Laravel, Vue. Ich arbeite dort, wo sich das Signal nicht mehr vom Rauschen unterscheidet.',
        'el' => 'Laurent Bernard-Cardascia — Tech Lead. Αρχιτεκτονική, PHP/Laravel, Vue. Δουλεύω εκεί όπου το σήμα δεν ξεχωρίζεται πλέον από τον θόρυβο.',
        'en' => 'Laurent Bernard-Cardascia — Tech Lead. Architecture, PHP/Laravel, Vue. I work where signal can no longer be distinguished from noise.',
        'es' => 'Laurent Bernard-Cardascia — Tech Lead. Arquitectura, PHP/Laravel, Vue. Trabajo donde la señal ya no se distingue del ruido.',
        'et' => 'Laurent Bernard-Cardascia — Tech Lead. Arhitektuur, PHP/Laravel, Vue. Töötан seal, kus signaali ei saa mürust eristada.',
        'fi' => 'Laurent Bernard-Cardascia — Tech Lead. Arkkitehtuuri, PHP/Laravel, Vue. Työskentelen siellä, jossa signaalia ei enää erota kohinasta.',
        'fr' => 'Laurent Bernard-Cardascia — Tech Lead. Architecture, PHP/Laravel, Vue. Je travaille là où le signal ne se distingue plus du bruit.',
        'ga' => 'Laurent Bernard-Cardascia — Tech Lead. Ailtireacht, PHP/Laravel, Vue. Oibrím áit ar stop an comhartha a bheith ar leithéid ar an torann.',
        'hr' => 'Laurent Bernard-Cardascia — Tech Lead. Arhitektura, PHP/Laravel, Vue. Radim tamo gdje se signal više ne razlikuje od šuma.',
        'hu' => 'Laurent Bernard-Cardascia — Tech Lead. Architektúra, PHP/Laravel, Vue. Ott dolgozom, ahol a jel már nem különbözik a zajától.',
        'it' => 'Laurent Bernard-Cardascia — Tech Lead. Architettura, PHP/Laravel, Vue. Lavoro dove il segnale non si distingue più dal rumore.',
        'lt' => 'Laurent Bernard-Cardascia — Tech Lead. Architektūra, PHP/Laravel, Vue. Dirbu vietoje, kur signalas nuo triukšmo nebesiskiria.',
        'lv' => 'Laurent Bernard-Cardascia — Tech Lead. Arhitektūra, PHP/Laravel, Vue. Es strādāju vietā, kur signāls vairs neatšķiras no traucējumiem.',
        'mt' => 'Laurent Bernard-Cardascia — Tech Lead. Arkitettura, PHP/Laravel, Vue. Jien nħaddem fejn is-sinjal ma jistgħux jinqasam mill-ħoss.',
        'nl' => 'Laurent Bernard-Cardascia — Tech Lead. Architectuur, PHP/Laravel, Vue. Ik werk daar waar het signaal niet meer te onderscheiden is van ruis.',
        'pl' => 'Laurent Bernard-Cardascia — Tech Lead. Architektura, PHP/Laravel, Vue. Pracuję tam, gdzie sygnał nie różni się już od szumu.',
        'pt' => 'Laurent Bernard-Cardascia — Tech Lead. Arquitetura, PHP/Laravel, Vue. Trabalho onde o sinal não se distingue mais do ruído.',
        'ro' => 'Laurent Bernard-Cardascia — Tech Lead. Arhitectură, PHP/Laravel, Vue. Lucrez acolo unde semnalul nu se mai distinge de zgomot.',
        'sk' => 'Laurent Bernard-Cardascia — Tech Lead. Architektúra, PHP/Laravel, Vue. Pracujem tam, kde sa signál už neodlišuje od šumu.',
        'sl' => 'Laurent Bernard-Cardascia — Tech Lead. Arhitektura, PHP/Laravel, Vue. Delam tam, kjer se signal ne loči več od šuma.',
        'sv' => 'Laurent Bernard-Cardascia — Tech Lead. Arkitektur, PHP/Laravel, Vue. Jag arbetar där signalen inte längre skiljer sig från bruset.',
    ],
    'skills' => [
        'bg' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Quality","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Сигурност","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tests de pénétration","CORS"]}]',
        'cs' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architektura & Kvalita","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Bezpečnost","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrační testy","CORS"]}]',
        'da' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arkitektur & Kvalitet","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastruktur","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sikkerhed","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrationstests","CORS"]}]',
        'de' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Qualität","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sicherheit","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrationstests","CORS"]}]',
        'el' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Qualité","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Ασφάλεια","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Δοκιμές διείσδυσης","CORS"]}]',
        'en' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistence","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Quality","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Security","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetration testing","CORS"]}]',
        'es' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Datos y Persistencia","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arquitectura y Calidad","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps e Infraestructura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Seguridad","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tests de penetración","CORS"]}]',
        'et' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standardid","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Andmed ja säilitamine","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Päringute optimeerimine","Skeemi kujundus"]},{"icon":"△","name":"Arhitektuur ja kvaliteet","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI kvaliteediväärad","Koodi ülevaatus"]},{"icon":"⚙","name":"DevOps ja infrastruktuur","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Turvalisus","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Määra piiramine","Penetratsioonitestid","CORS"]}]',
        'fi' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arkkitehtuuri & Laatu","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastruktuuri","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Turvallisuus","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetraatiotestit","CORS"]}]',
        'fr' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Qualité","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sécurité","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tests de pénétration","CORS"]}]',
        'ga' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Sonraí & Seasmhachta","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Ailtireacht & Caighdeán","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Bonneagar","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Slándáil","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tástáil dhraíochta","CORS"]}]',
        'hr' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arhitektura & Kvaliteta","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastruktura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sigurnost","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Testovi penetracije","CORS"]}]',
        'hu' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Adatok és Perzisztencia","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architektúra és Minőség","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps és Infrastruktúra","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Biztonság","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrációs tesztek","CORS"]}]',
        'it' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Dati & Persistenza","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architettura & Qualità","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastruttura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sicurezza","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Test di penetrazione","CORS"]}]',
        'lt' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Duomenys ir jų saugojimas","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architektūra ir kokybė","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps ir infrastruktūra","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Saugumas","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tests de pénétration","CORS"]}]',
        'lv' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Dati un persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arhitektūra un kvalitāte","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps un infrastruktūra","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Drošība","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrācijas testi","CORS"]}]',
        'mt' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistenza","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arkitettura & Kwalità","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastruttura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Sigurtà","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Tests ta\' penetrazzjoni","CORS"]}]',
        'nl' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Gegevens & Persistentie","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architectuur & Kwaliteit","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructuur","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Beveiliging","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetratietests","CORS"]}]',
        'pl' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architecture & Qualité","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Bezpieczeństwo","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Testy penetracyjne","CORS"]}]',
        'pt' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Dados & Persistência","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arquitetura & Qualidade","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infraestrutura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Segurança","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Testes de penetração","CORS"]}]',
        'ro' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Date & Persistență","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arhitectură & Calitate","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructură","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Securitate","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Teste de penetrare","CORS"]}]',
        'sk' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Architektúra & Kvalita","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infraštruktúra","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Bezpečnosť","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetračné testy","CORS"]}]',
        'sl' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Podatki in trajnost","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Optimizacija poizvedb","Oblikovanje sheme"]},{"icon":"△","name":"Arhitektura in kakovost","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Pregled koda"]},{"icon":"⚙","name":"DevOps in infrastruktura","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Varnost","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Omejitev hitrosti","Testi penetracije","CORS"]}]',
        'sv' => '[{"icon":"⬡","name":"Backend","techs":["PHP 8.5","Laravel 13","Symfony","API Platform","FrankenPHP / Octane","REST API","PSR standards","Composer"]},{"icon":"◈","name":"Frontend","techs":["Vue 3.5","React / Next.js","TypeScript","Vite","Tailwind CSS","Playwright","jQuery"]},{"icon":"⊙","name":"Data & Persistance","techs":["PostgreSQL","MySQL / MariaDB","Redis","Elasticsearch","ELK Stack","Query optimization","Schema design"]},{"icon":"△","name":"Arkitektur & Kvalitet","techs":["Clean Architecture","SOLID","DDD","PHPStan lvl 8","PHPUnit / Vitest","TDD","CI quality gates","Code review"]},{"icon":"⚙","name":"DevOps & Infrastructure","techs":["Docker","GitHub Actions","Jenkins","Nginx","Caddy","Sentry","Telescope","Xdebug"]},{"icon":"⊗","name":"Säkerhet","techs":["JWT","OAuth 2.0","OpenID Connect","TOTP / 2FA","Sanctum","OWASP Top 10","Rate limiting","Penetrationstester","CORS"]}]',
    ],
];
